//! Compute kernel dispatch facades.

pub mod affine;
pub mod const_set;
pub mod copy;
pub mod dispatch;
pub mod elementwise;
pub mod gather;
pub mod gemm;
pub mod gemv;
pub mod q4k;
pub mod q5q8;
pub mod rms_norm;
pub mod rope;
pub mod softmax;
pub mod test_fill_bf16;
pub mod test_fill_f16;
pub mod test_fill_f32;
pub mod test_fill_f4;
pub mod test_fill_f64;
pub mod test_fill_f6e2m3;
pub mod test_fill_f6e3m2;
pub mod test_fill_f8e4m3;
pub mod test_fill_f8e8m0;
pub mod test_fill_i16;
pub mod test_fill_i32;
pub mod test_fill_i64;
pub mod test_fill_u32;
pub mod test_fill_u8;
pub mod binary_slang;
pub mod cmp_slang;
pub mod where_slang;
pub mod copy2d_slang;
pub mod gather_idx_slang;
pub mod reduce_slang;
pub mod pool2d_slang;
pub mod upsample_slang;
pub mod conv_slang;
pub mod scatter_slang;
pub mod unary_slang;

pub use affine::call_affine_f32;
pub use const_set::call_const_set_f32;
pub use copy::call_copy_f32;
pub use elementwise::{call_elem_binary_f32, call_elem_unary_f32};
pub use gather::call_gather_f32;
pub use gemm::call_gemm_f32;
pub use gemv::{call_gemv_f32, call_gemv_t_f32};
pub use q4k::{call_q4k_dequant_f32, call_q4k_qmatvec_f32, call_q6k_dequant_f32};
pub use q5q8::{call_q50_dequant_f32, call_q5k_dequant_f32, call_q80_dequant_f32};
pub use rms_norm::call_rms_norm_f32;
pub use rope::call_rope_f32;
pub use softmax::call_softmax_last_dim_f32;
pub use test_fill_bf16::{call_test_fill_bf16_emulated, call_test_fill_bf16_native};
pub use test_fill_f16::call_test_fill_f16;
pub use test_fill_f32::call_test_fill_f32;
pub use test_fill_f4::call_test_fill_f4;
pub use test_fill_f64::call_test_fill_f64;
pub use test_fill_f6e2m3::call_test_fill_f6e2m3;
pub use test_fill_f6e3m2::call_test_fill_f6e3m2;
pub use test_fill_f8e4m3::call_test_fill_f8e4m3;
pub use test_fill_f8e8m0::call_test_fill_f8e8m0;
pub use test_fill_i16::call_test_fill_i16;
pub use test_fill_i32::call_test_fill_i32;
pub use test_fill_i64::call_test_fill_i64;
pub use test_fill_u32::call_test_fill_u32;
pub use test_fill_u8::call_test_fill_u8;
pub use binary_slang::call_binary_slang_f32;
pub use cmp_slang::call_cmp_slang_f32;
pub use where_slang::call_where_slang_f32;
pub use copy2d_slang::call_copy2d_slang_f32;
pub use gather_idx_slang::call_gather_idx_slang_f32;
pub use reduce_slang::call_reduce_slang_f32;
pub use pool2d_slang::call_pool2d_slang_f32;
pub use upsample_slang::call_upsample_slang_f32;
pub use conv_slang::call_conv_slang_f32;
pub use scatter_slang::call_scatter_slang_f32;
pub use unary_slang::call_unary_slang_f32;
